# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Infinitude Server add-on
version: "1.2.0"
slug: infinitude_1F
description: Infinitude web server
url: "https://github.com/Tjcav/infinitude_1F"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-infinitude_1F"
